### ISSUE TITLE
expected keys for credit card have changed for me

### ISSUE THREAD

**Issue by psychoticbeef** [siddhantgoel/beancount-dkb#85]
Hi,

just today used this for the first time (thanks for sharing!). I cannot use poetry here right now, so I cannot run tests, hence I am unable to provide a pull request. Are you seeing the change to the CSV too?

-            expected_keys = set(['Von:', 'Bis:', 'Saldo:', 'Datum:'])
+            expected_keys = set(['Saldo:', 'Datum:', 'Zeitraum:'])

Hth,
Psychoticbeef

**Comment by siddhantgoel** [comment]
This happens when, while you're downloading the CSV files, in the Zeitraum section you choose a predefined value (like "letzten 30 Tage") instead of setting fixed dates in the Vom/Bis fields.

I'll try to find time for this next week. Until then I would recommend please set the Vom/Bis fields when you're downloading the CSV files instead of choosing the "Auswahl" option.

**Comment by psychoticbeef** [comment]
Ohh, sorry. Makes sense. If I truly happen to need this feature, I'd make a pull request. Range is absolutely fine. Thanks!
